//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetCities
    {
        public int Id_City { get; set; }
        public int Id_Voivode { get; set; }
        public string LocalizationCity { get; set; }
    
        public virtual AspNetVoivodes AspNetVoivodes { get; set; }
    }
}
