//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetProducts()
        {
            this.AspNetImages = new HashSet<AspNetImages>();
            this.AspNetRatings = new HashSet<AspNetRatings>();
        }
    
        public int Id_Product { get; set; }
        public int Id_Category { get; set; }
        public string ProductDescription { get; set; }
        public string ProductName { get; set; }
        public int Opinion_Counter { get; set; }
        public Nullable<int> AvarageTaste { get; set; }
        public Nullable<int> AvarageService { get; set; }
        public Nullable<int> AvarageIngredients { get; set; }
        public string Who { get; set; }
        public string UniqName { get; set; }
        public Nullable<int> Id_Place { get; set; }
        public bool CzyDobre { get; set; }
        public string Objections { get; set; }
    
        public virtual AspNetCategories AspNetCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetImages> AspNetImages { get; set; }
        public virtual AspNetPlaces AspNetPlaces { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRatings> AspNetRatings { get; set; }
    }
}
