//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRatingPictures
    {
        public int Id_Picture { get; set; }
        public string Url { get; set; }
        public Nullable<int> Id_Rating { get; set; }
    
        public virtual AspNetRatings AspNetRatings { get; set; }
    }
}
