//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRestaurant
    {
        public int Id_Restaurant { get; set; }
        public Nullable<int> Id_Localization { get; set; }
        public Nullable<int> Id_RestaurantOpening { get; set; }
        public string RestaurantPhoneNumber { get; set; }
        public string RestaurantEmail { get; set; }
        public string RestaurantFanpage { get; set; }
        public string RestaurantImage { get; set; }
        public string RestaurantName { get; set; }
    
        public virtual AspNetRestaurantOpening AspNetRestaurantOpening { get; set; }
    }
}
