//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRestaurantsType
    {
        public int Id_RestaurantType { get; set; }
        public string RestaurantTypeName { get; set; }
        public string RestaurantTypeDescription { get; set; }
    }
}
