//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRestaurantOpenings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRestaurantOpenings()
        {
            this.AspNetRestaurants = new HashSet<AspNetRestaurants>();
        }
    
        public int Id_RestaurantOpening { get; set; }
        public Nullable<int> Id_RestaurantCalendar { get; set; }
    
        public virtual AspNetRestaurantCalendarDays AspNetRestaurantCalendarDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRestaurants> AspNetRestaurants { get; set; }
    }
}
