//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetReview
    {
        public string Id_Review { get; set; }
        public string ReviewContent { get; set; }
        public int Id_Product { get; set; }
        public string Id_User { get; set; }
    
        public virtual AspNetProduct AspNetProduct { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
