//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetCategories> AspNetCategories { get; set; }
        public virtual DbSet<AspNetCities> AspNetCities { get; set; }
        public virtual DbSet<AspNetCoordinates> AspNetCoordinates { get; set; }
        public virtual DbSet<AspNetImages> AspNetImages { get; set; }
        public virtual DbSet<AspNetIngredients> AspNetIngredients { get; set; }
        public virtual DbSet<AspNetPlaces> AspNetPlaces { get; set; }
        public virtual DbSet<AspNetProducts> AspNetProducts { get; set; }
        public virtual DbSet<AspNetRatingPictures> AspNetRatingPictures { get; set; }
        public virtual DbSet<AspNetRatings> AspNetRatings { get; set; }
        public virtual DbSet<AspNetRestaurantCalendarDays> AspNetRestaurantCalendarDays { get; set; }
        public virtual DbSet<AspNetRestaurantCalendars> AspNetRestaurantCalendars { get; set; }
        public virtual DbSet<AspNetRestaurantOpenings> AspNetRestaurantOpenings { get; set; }
        public virtual DbSet<AspNetRestaurants> AspNetRestaurants { get; set; }
        public virtual DbSet<AspNetRestaurantsTypes> AspNetRestaurantsTypes { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetVoivodes> AspNetVoivodes { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
    }
}
