//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CzyDobre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetCategory> AspNetCategories { get; set; }
        public virtual DbSet<AspNetLocalization> AspNetLocalizations { get; set; }
        public virtual DbSet<AspNetProduct> AspNetProducts { get; set; }
        public virtual DbSet<AspNetRating> AspNetRatings { get; set; }
        public virtual DbSet<AspNetRestaurantCalendar> AspNetRestaurantCalendars { get; set; }
        public virtual DbSet<AspNetRestaurantCalendarDay> AspNetRestaurantCalendarDays { get; set; }
        public virtual DbSet<AspNetRestaurantOpening> AspNetRestaurantOpenings { get; set; }
        public virtual DbSet<AspNetRestaurant> AspNetRestaurants { get; set; }
        public virtual DbSet<AspNetRestaurantsType> AspNetRestaurantsTypes { get; set; }
        public virtual DbSet<AspNetReview> AspNetReviews { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<AspNetCoordinate> AspNetCoordinates { get; set; }
        public virtual DbSet<AspNetImage> AspNetImages { get; set; }
        public virtual DbSet<AspNetIngredient> AspNetIngredients { get; set; }
        public virtual DbSet<AspNetTaste> AspNetTastes { get; set; }
    }
}
